# Rescue DAG file, created after running
#   the Cats_and_Dogs-0.dag DAG file
# Created 9/10/2020 22:38:12 UTC
# Rescue DAG version: 2.0.1 (partial)
#
# Total number of Nodes: 30
# Nodes premarked DONE: 24
# Nodes that failed: 0
#   <ENDLIST>

DONE create_dir_Cats_and_Dogs_0_local
RETRY create_dir_Cats_and_Dogs_0_local 100
DONE stage_in_remote_local_2_0
RETRY stage_in_remote_local_2_0 100
DONE stage_in_remote_local_1_0
RETRY stage_in_remote_local_1_0 100
DONE stage_in_remote_local_0_0
RETRY stage_in_remote_local_0_0 100
DONE stage_in_local_local_4_0
RETRY stage_in_local_local_4_0 100
DONE stage_in_local_local_0_0
RETRY stage_in_local_local_0_0 100
DONE stage_in_remote_local_4_0
RETRY stage_in_remote_local_4_0 100
DONE stage_in_remote_local_3_0
RETRY stage_in_remote_local_3_0 100
DONE preprocess1_py_ID0000001
RETRY preprocess1_py_ID0000001 100
DONE Augmentation_py_ID0000002
RETRY Augmentation_py_ID0000002 100
DONE clean_up_local_level_3_0
RETRY clean_up_local_level_3_0 100
DONE stage_out_local_local_0_0
RETRY stage_out_local_local_0_0 100
DONE Data_Split_py_ID0000003
RETRY Data_Split_py_ID0000003 100
DONE stage_out_local_local_1_0
RETRY stage_out_local_local_1_0 100
DONE register_local_0_0
RETRY register_local_0_0 100
DONE clean_up_local_level_4_0
RETRY clean_up_local_level_4_0 100
DONE stage_out_local_local_2_0
RETRY stage_out_local_local_2_0 100
DONE VGG_model_py_ID0000004
RETRY VGG_model_py_ID0000004 100
DONE register_local_1_0
RETRY register_local_1_0 100
DONE clean_up_local_level_5_0
RETRY clean_up_local_level_5_0 100
DONE register_local_2_0
RETRY register_local_2_0 100
DONE stage_out_local_local_3_0
RETRY stage_out_local_local_3_0 100
RETRY hpo_checkpointing_py_ID0000005 100
DONE clean_up_local_level_6_0
RETRY clean_up_local_level_6_0 100
DONE register_local_3_0
RETRY register_local_3_0 100
RETRY stage_out_local_local_4_0 100
RETRY clean_up_local_level_7_0 100
RETRY register_local_4_0 100
RETRY clean_up_local_level_8_0 100
RETRY cleanup_Cats_and_Dogs_0_local 100
